ID_PARA_ESCOLA = {
  39 : "CM Antonio Rodrigues Bayma",
  40 : "EM Antenor Gomes Viana Junior",
  41 : "UI Deputado Alexandre Costa",
  42 : "UI Doutor Achiles Cruz",
  43 : "UI Izaura Costa",
  44 : "UI Joao Lisboa",
  45 : "UI Nossa Senhora dos Remedios",
  46 : "UI Presidente John Kennedy",
  47 : "UI Professora Raimunda Barbosa G de Jesus",
  48 : "UI Professora Rita de Cassia Azevedo",
  49 : "UI Professora Suely Reis",
  50 : "UEM Jose Osmar Fernandes",
  51 : "UEM Zeferino Borges da Cunha",
  52 : "UIM Alderico Machado",
  53 : "UIM Antonio Edson Rodrigues",
  54 : "UIM Antonio Rosa de Lima",
  55 : "UIM Coelho Neto",
  56 : "UIM Coronel Gervasio Costa",
  57 : "UIM Debora Pereira - Colegio Militar 2 de Julho",
  58 : "UIM Filomena Machado Teixeira",
  59 : "UIM Flora Alves de Andrade",
  60 : "UIM Gentil Frazao",
  61 : "UIM Guiomar Cruz Assuncao",
  62 : "UIM Helio de Sousa Queiroz",
  63 : "UIM Jacira Goncalves Vila Nova",
  64 : "UIM Joaquim Francisco de Sousa",
  65 : "UIM Joao Santino Torres",
  66 : "UIM Jose Castro",
  67 : "UIM Luis Falcao",
  68 : "UIM Marly Sarney Costa",
  69 : "UIM Nossa Senhora de Nazare - Nazare do Bruno",
  70 : "UIM Paulo Freire",
  71 : "UIM Prefeito Eziquio Barros Filho",
  72 : "UIM Professora Evangelina Caetano",
  73 : "UIM Professora Inez Evangelista",
  74 : "UIM Professora Magnolia Herminia Araujo",
  75 : "UIM Professora Marinalva Soares Guimaraes",
  76 : "UIM Renato Vila Nova",
  77 : "UIM Santa Catarina de Laboure",
  78 : "UIM Sao Raimundo",
  79 : "UIM Sinha Castelo",
}